# Copyright: Ajatt-Tools and contributors; https://github.com/Ajatt-Tools
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
from typing import Final

from ..mecab_controller.basic_types import PartOfSpeech

MAX_ATTACHED = 4
SKIP_COLORING: Final[frozenset[PartOfSpeech]] = frozenset((
    PartOfSpeech.other,
    PartOfSpeech.filler,
    PartOfSpeech.particle,
    PartOfSpeech.symbol,
))
DETACH_POS: Final[frozenset[PartOfSpeech]] = frozenset((
    PartOfSpeech.adverb,
    PartOfSpeech.noun,
    PartOfSpeech.adnominal_adjective,
    PartOfSpeech.interjection,
))
DETACH_WORDS: Final[frozenset[str]] = frozenset((
    "ほしい",
    "だ",
    "って",
    "やっ",
    "です",
    "いれ",
    "おく",
    "させる",
    "ごめん",
    "もらう",
    "いく",
    "くださる",
    "くる",
    "から",
    "かねる",
    "あの",
    "すぐ",
    "ね",
    "か",
    "なぁ",
    "なあ",
    "とか",
    "けど",
    "だけ",
    "だろ",
    "でしょ",
    "なる",
    "は",
    "が",
    "の",
    "しまう",
    "おる",
    "ある",
    "な",
    "じゃ",
    "らしい",
    "し",
    "も",
    "ほど",
    "いける",
    "たらしい",
    "に",
    "ら",
    "ぞ",
    "だって",
    "よう",
    "として",
    "よ",
    "を",
))
DETACH_HEADWORDS: Final[frozenset[str]] = frozenset((
    "おいしい",
    "しかも",
    "やる",
    "しまう",
    "いれ",
    "させる",
    "ごめん",
    "もらう",
    "いく",
    "くださる",
    "くる",
    "から",
    "かねる",
    "あの",
    "すぐ",
    "ね",
    "か",
    "なぁ",
    "なあ",
    "とか",
    "けど",
    "だけ",
    "だろ",
    "でしょ",
    "なる",
    "は",
    "が",
    "の",
    "しまう",
    "おる",
    "ある",
    "な",
    "じゃ",
    "らしい",
    "し",
    "も",
    "ほど",
    "いける",
    "たらしい",
    "ぎす",
    "すぎる",
    "くれる",
    "もらう",
    "あげる",
    "できる",
    "みる",
    "べし",
    "おける",
    "おく",
    "まくる",
    "いい",
    "ていう",
    "くらい",
    "ながら",
    "と",
    "でも",
    "まで",
    "ふためく",
    "はおる",
    "つつ",
))
TAPE_PAIRS: Final[frozenset[tuple[str, str]]] = frozenset((
    ("ませ", "ん"),
    ("でき", "ん"),
    ("しや", "が"),
    ("が", "って"),
    ("て", "くる"),
    ("し", "なさい"),
))
DETACH_PAIRS: Final[frozenset[tuple[str, str]]] = frozenset((
    ("て", "なく"),
    ("く", "ない"),
    ("しく", "ない"),
    ("く", "なかっ"),
    ("しく", "なかっ"),
    ("て", "い"),
    ("たく", "ない"),
))
